"""Configuration constants and the supported environment-variable contract."""

from __future__ import annotations

from enum import StrEnum
from pathlib import Path
from typing import Literal

PROJECT_ROOT = Path(__file__).resolve().parents[3]
AuthProviderName = Literal["none", "static", "jwt", "ldap", "kerberos", "ldap_kerberos"]
DatabaseProviderName = Literal["none", "oracle", "sqlalchemy"]
ModelProviderName = Literal["openai", "azure_openai"]
MongoDBCollectionName = Literal[
    "documents",
    "chat_history",
    "cache",
    "semantic_cache",
]
DEFAULT_MONGODB_COLLECTIONS: dict[MongoDBCollectionName, str] = {
    "documents": "documents",
    "chat_history": "chat_history",
    "cache": "cache",
    "semantic_cache": "semantic_cache",
}
DEFAULT_MONGODB_VECTOR_INDEX = "vector_index"
DEFAULT_TAG_SCOPE_RULES: dict[str, tuple[str, ...]] = {
    "admin": ("admin",),
    "destructive": ("admin",),
    "external": ("external",),
    "write": ("write",),
}
OPENAI_API_KEY_PLACEHOLDER = "your-api-key"
DEFAULT_AZURE_OPENAI_TOKEN_SCOPE = "https://cognitiveservices.azure.com/.default"


class EnvironmentVariable(StrEnum):
    """Environment variables consumed by :meth:`Settings.from_env`."""

    AZURE_CLIENT_ID = "AZURE_CLIENT_ID"
    AZURE_CLIENT_SECRET = "AZURE_CLIENT_SECRET"
    AZURE_OPENAI_API_VERSION = "AZURE_OPENAI_API_VERSION"
    AZURE_OPENAI_EMBEDDING_MODEL_DEPLOYMENT = "AZURE_OPENAI_EMBEDDING_MODEL_DEPLOYMENT"
    AZURE_OPENAI_ENDPOINT = "AZURE_OPENAI_ENDPOINT"
    AZURE_OPENAI_LARGE_LANGUAGE_MODEL_DEPLOYMENT = "AZURE_OPENAI_LARGE_LANGUAGE_MODEL_DEPLOYMENT"
    AZURE_OPENAI_SMALL_LANGUAGE_MODEL_DEPLOYMENT = "AZURE_OPENAI_SMALL_LANGUAGE_MODEL_DEPLOYMENT"
    AZURE_OPENAI_TOKEN_SCOPE = "AZURE_OPENAI_TOKEN_SCOPE"
    AZURE_TENANT_ID = "AZURE_TENANT_ID"
    MCP_PORTAL_AUDIT_ENABLED = "MCP_PORTAL_AUDIT_ENABLED"
    MCP_PORTAL_AUTH_JWT_ALGORITHM = "MCP_PORTAL_AUTH_JWT_ALGORITHM"
    MCP_PORTAL_AUTH_JWT_AUDIENCE = "MCP_PORTAL_AUTH_JWT_AUDIENCE"
    MCP_PORTAL_AUTH_JWT_ISSUER = "MCP_PORTAL_AUTH_JWT_ISSUER"
    MCP_PORTAL_AUTH_JWT_JWKS_URI = "MCP_PORTAL_AUTH_JWT_JWKS_URI"
    MCP_PORTAL_AUTH_JWT_PUBLIC_KEY = "MCP_PORTAL_AUTH_JWT_PUBLIC_KEY"
    MCP_PORTAL_AUTH_KERBEROS_HOSTNAME = "MCP_PORTAL_AUTH_KERBEROS_HOSTNAME"
    MCP_PORTAL_AUTH_KERBEROS_KEYTAB = "MCP_PORTAL_AUTH_KERBEROS_KEYTAB"
    MCP_PORTAL_AUTH_KERBEROS_SCOPES = "MCP_PORTAL_AUTH_KERBEROS_SCOPES"
    MCP_PORTAL_AUTH_KERBEROS_SERVICE = "MCP_PORTAL_AUTH_KERBEROS_SERVICE"
    MCP_PORTAL_AUTH_LDAP_BASE_DN = "MCP_PORTAL_AUTH_LDAP_BASE_DN"
    MCP_PORTAL_AUTH_LDAP_BIND_DN = "MCP_PORTAL_AUTH_LDAP_BIND_DN"
    MCP_PORTAL_AUTH_LDAP_BIND_PASSWORD = "MCP_PORTAL_AUTH_LDAP_BIND_PASSWORD"
    MCP_PORTAL_AUTH_LDAP_CA_CERT_FILE = "MCP_PORTAL_AUTH_LDAP_CA_CERT_FILE"
    MCP_PORTAL_AUTH_LDAP_CONNECT_TIMEOUT = "MCP_PORTAL_AUTH_LDAP_CONNECT_TIMEOUT"
    MCP_PORTAL_AUTH_LDAP_SCOPES = "MCP_PORTAL_AUTH_LDAP_SCOPES"
    MCP_PORTAL_AUTH_LDAP_SEARCH_FILTER = "MCP_PORTAL_AUTH_LDAP_SEARCH_FILTER"
    MCP_PORTAL_AUTH_LDAP_START_TLS = "MCP_PORTAL_AUTH_LDAP_START_TLS"
    MCP_PORTAL_AUTH_LDAP_URI = "MCP_PORTAL_AUTH_LDAP_URI"
    MCP_PORTAL_AUTH_LDAP_USER_DN_TEMPLATE = "MCP_PORTAL_AUTH_LDAP_USER_DN_TEMPLATE"
    MCP_PORTAL_AUTH_PROVIDER = "MCP_PORTAL_AUTH_PROVIDER"
    MCP_PORTAL_AUTH_REQUIRED_LINUX_GROUPS = "MCP_PORTAL_AUTH_REQUIRED_LINUX_GROUPS"
    MCP_PORTAL_AUTH_REQUIRED_SCOPES = "MCP_PORTAL_AUTH_REQUIRED_SCOPES"
    MCP_PORTAL_AUTH_RESOURCE_SERVER_URL = "MCP_PORTAL_AUTH_RESOURCE_SERVER_URL"
    MCP_PORTAL_AUTH_STATIC_CLIENT_ID = "MCP_PORTAL_AUTH_STATIC_CLIENT_ID"
    MCP_PORTAL_AUTH_STATIC_SCOPES = "MCP_PORTAL_AUTH_STATIC_SCOPES"
    MCP_PORTAL_AUTH_STATIC_TOKEN = "MCP_PORTAL_AUTH_STATIC_TOKEN"
    MCP_PORTAL_AUTHZ_NAMESPACE_SCOPES = "MCP_PORTAL_AUTHZ_NAMESPACE_SCOPES"
    MCP_PORTAL_AUTHZ_NAMESPACE_LINUX_GROUPS = "MCP_PORTAL_AUTHZ_NAMESPACE_LINUX_GROUPS"
    MCP_PORTAL_AUTHZ_TAG_SCOPES = "MCP_PORTAL_AUTHZ_TAG_SCOPES"
    MCP_PORTAL_CIRCUIT_BREAKER_FAILURE_THRESHOLD = "MCP_PORTAL_CIRCUIT_BREAKER_FAILURE_THRESHOLD"
    MCP_PORTAL_CIRCUIT_BREAKER_RECOVERY_SECONDS = "MCP_PORTAL_CIRCUIT_BREAKER_RECOVERY_SECONDS"
    MCP_PORTAL_COST_ACCOUNTING_ENABLED = "MCP_PORTAL_COST_ACCOUNTING_ENABLED"
    MCP_PORTAL_COST_CURRENCY = "MCP_PORTAL_COST_CURRENCY"
    MCP_PORTAL_DATABASE_PROVIDER = "MCP_PORTAL_DATABASE_PROVIDER"
    MCP_PORTAL_DATABASE_SQLALCHEMY_URL = "MCP_PORTAL_DATABASE_SQLALCHEMY_URL"
    MCP_PORTAL_DOWNSTREAM_TIMEOUT_SECONDS = "MCP_PORTAL_DOWNSTREAM_TIMEOUT_SECONDS"
    MCP_PORTAL_EGRESS_ALLOWED_HOSTS = "MCP_PORTAL_EGRESS_ALLOWED_HOSTS"
    MCP_PORTAL_EGRESS_DESTINATION_CLASSIFICATIONS = "MCP_PORTAL_EGRESS_DESTINATION_CLASSIFICATIONS"
    MCP_PORTAL_EGRESS_SENSITIVE_FIELD_ACTION = "MCP_PORTAL_EGRESS_SENSITIVE_FIELD_ACTION"
    MCP_PORTAL_HEALTH_ENABLED = "MCP_PORTAL_HEALTH_ENABLED"
    MCP_PORTAL_HEALTH_PATH = "MCP_PORTAL_HEALTH_PATH"
    MCP_PORTAL_HTTP_PATH = "MCP_PORTAL_HTTP_PATH"
    MCP_PORTAL_JSON_RESPONSE = "MCP_PORTAL_JSON_RESPONSE"
    MCP_PORTAL_LOG_PAYLOAD_LENGTHS = "MCP_PORTAL_LOG_PAYLOAD_LENGTHS"
    MCP_PORTAL_MAX_CONCURRENT_REQUESTS = "MCP_PORTAL_MAX_CONCURRENT_REQUESTS"
    MCP_PORTAL_METRICS_ENABLED = "MCP_PORTAL_METRICS_ENABLED"
    MCP_PORTAL_METRICS_INCLUDE_TENANT = "MCP_PORTAL_METRICS_INCLUDE_TENANT"
    MCP_PORTAL_MIDDLEWARE_ENABLED = "MCP_PORTAL_MIDDLEWARE_ENABLED"
    MCP_PORTAL_MULTI_INSTANCE = "MCP_PORTAL_MULTI_INSTANCE"
    MCP_PORTAL_MODEL_PROVIDER = "MCP_PORTAL_MODEL_PROVIDER"
    MCP_PORTAL_MONGODB_CONNECTION_STRING = "MCP_PORTAL_MONGODB_CONNECTION_STRING"
    MCP_PORTAL_MONGODB_DATABASE = "MCP_PORTAL_MONGODB_DATABASE"
    MCP_PORTAL_MONGODB_VECTOR_SEARCH_INDEX = "MCP_PORTAL_MONGODB_VECTOR_SEARCH_INDEX"
    MCP_PORTAL_NAMESPACE_ALLOWLIST = "MCP_PORTAL_NAMESPACE_ALLOWLIST"
    MCP_PORTAL_NAMESPACE_DISCOVERY_STRICT = "MCP_PORTAL_NAMESPACE_DISCOVERY_STRICT"
    MCP_PORTAL_ORACLE_DSN = "MCP_PORTAL_ORACLE_DSN"
    MCP_PORTAL_ORACLE_PASSWORD = "MCP_PORTAL_ORACLE_PASSWORD"
    MCP_PORTAL_ORACLE_POOL_MAX = "MCP_PORTAL_ORACLE_POOL_MAX"
    MCP_PORTAL_ORACLE_POOL_MIN = "MCP_PORTAL_ORACLE_POOL_MIN"
    MCP_PORTAL_ORACLE_USER = "MCP_PORTAL_ORACLE_USER"
    MCP_PORTAL_PRICING_VERSION = "MCP_PORTAL_PRICING_VERSION"
    MCP_PORTAL_PRODUCTION_REQUIRE_AUTH = "MCP_PORTAL_PRODUCTION_REQUIRE_AUTH"
    MCP_PORTAL_RATE_LIMIT_BURST = "MCP_PORTAL_RATE_LIMIT_BURST"
    MCP_PORTAL_RATE_LIMIT_PER_SECOND = "MCP_PORTAL_RATE_LIMIT_PER_SECOND"
    MCP_PORTAL_READINESS_PATH = "MCP_PORTAL_READINESS_PATH"
    MCP_PORTAL_REQUIRE_TENANT = "MCP_PORTAL_REQUIRE_TENANT"
    MCP_PORTAL_RESPONSE_MAX_BYTES = "MCP_PORTAL_RESPONSE_MAX_BYTES"
    MCP_PORTAL_STATELESS_HTTP = "MCP_PORTAL_STATELESS_HTTP"
    MCP_PORTAL_STRUCTURED_LOGGING = "MCP_PORTAL_STRUCTURED_LOGGING"
    MCP_PORTAL_TASK_MAX_CONCURRENT_PER_SUBJECT = "MCP_PORTAL_TASK_MAX_CONCURRENT_PER_SUBJECT"
    MCP_PORTAL_TASK_MAX_TTL_SECONDS = "MCP_PORTAL_TASK_MAX_TTL_SECONDS"
    MCP_PORTAL_TENANT_CLAIM = "MCP_PORTAL_TENANT_CLAIM"
    MCP_PORTAL_TOOL_CONCURRENCY_LIMITS = "MCP_PORTAL_TOOL_CONCURRENCY_LIMITS"
    MCP_PORTAL_TOOL_TIMEOUT_OVERRIDES = "MCP_PORTAL_TOOL_TIMEOUT_OVERRIDES"
    MCP_PORTAL_TOOL_TIMEOUT_SECONDS = "MCP_PORTAL_TOOL_TIMEOUT_SECONDS"
    OPENAI_API_KEY = "OPENAI_API_KEY"
    OPENAI_EMBEDDING_MODEL = "OPENAI_EMBEDDING_MODEL"
    OPENAI_LARGE_LANGUAGE_MODEL = "OPENAI_LARGE_LANGUAGE_MODEL"
    OPENAI_SMALL_LANGUAGE_MODEL = "OPENAI_SMALL_LANGUAGE_MODEL"
    OTEL_EXPORTER_OTLP_ENDPOINT = "OTEL_EXPORTER_OTLP_ENDPOINT"
    OTEL_SERVICE_NAME = "OTEL_SERVICE_NAME"


ENVIRONMENT_VARIABLE_NAMES = frozenset(variable.value for variable in EnvironmentVariable)
